# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPbxylj233p_KCp0b8wXPNG5yDEg2keg
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

df = pd.read_csv('streamlit_dataset.csv')

st.set_page_config(
    page_title="Економічний дашборд",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для економічного аналізу підприємств'
    }
)

# Увімкнути темну тему
alt.themes.enable("dark")

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")

# Кнопка для скидання фільтрів (через query params або сесію)
if st.sidebar.button("Скинути фільтри"):
    st.experimental_rerun()

# Фільтри
selected_year = st.sidebar.selectbox("Оберіть рік", sorted(df["Year"].unique()))
selected_regions = st.sidebar.multiselect("Регіони", df["Region"].unique(), default=df["Region"].unique())
selected_industries = st.sidebar.multiselect("Галузі", df["Industry"].unique(), default=df["Industry"].unique())
selected_scenario = st.sidebar.radio("Сценарій", df["Scenario"].unique())

min_roi = st.sidebar.slider("Мінімальний ROI", min_value=round(df["ROI"].min(), 2),
                            max_value=round(df["ROI"].max(), 2), value=0.0, step=0.05)

# Чекбокси для відображення
show_map = st.sidebar.checkbox("🗺 Показати карту компаній")
show_scatter = st.sidebar.checkbox("📉 Показати графік ROI vs Investment")

# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown("📘 **Інструкція**: \nФільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.")
st.sidebar.markdown("👨‍💼 **Автор**: Data Science Department")

# ---------------------------------
# 🔽 Фільтрація
# ---------------------------------

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_regions)) &
    (df["Industry"].isin(selected_industries)) &
    (df["Scenario"] == selected_scenario) &
    (df["ROI"] >= min_roi)
]

# ---------------------------------
# 🧾 Основна панель
# ---------------------------------

st.title("📊 Економічний дашборд компаній")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} компаній")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered_companies.csv",
    mime="text/csv"
)

# Таблиця результатів
st.dataframe(df_filtered)

# Карта компаній
if show_map:
    st.subheader("🗺 Географія компаній")
    st.map(df_filtered[['Latitude', 'Longitude']])

# Scatter-графік ROI ~ Investment
if show_scatter:
    st.subheader("📉 ROI ~ Investment (Altair)")
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x='Investment:Q',
        y='ROI:Q',
        color='Industry:N',
        tooltip=['Company', 'Investment', 'ROI']
    ).interactive().properties(
        width=700, height=400
    )
    st.altair_chart(chart, use_container_width=True)
