# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPbxylj233p_KCp0b8wXPNG5yDEg2keg
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

df = pd.read_csv('streamlit_dataset.csv')

st.set_page_config(
    page_title="Економічний дашборд",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для економічного аналізу підприємств'
    }
)

# --- Ініціалізація фільтрів у session_state ---
default_year = sorted(df["Year"].unique())[0]
default_regions = list(df["Region"].unique())
default_industries = list(df["Industry"].unique())
default_scenario = df["Scenario"].unique()[0]
default_max_budget = int(df["AdBudget"].max())

if "year" not in st.session_state:
    st.session_state.year = default_year
if "regions" not in st.session_state:
    st.session_state.regions = default_regions
if "industries" not in st.session_state:
    st.session_state.industries = default_industries
if "scenario" not in st.session_state:
    st.session_state.scenario = default_scenario
if "max_adbudget" not in st.session_state:
    st.session_state.max_adbudget = default_max_budget

# Увімкнути темну тему
alt.themes.enable("dark")

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")

# Кнопка скидання
if st.sidebar.button("Скинути фільтри"):
    st.session_state.year = default_year
    st.session_state.regions = default_regions
    st.session_state.industries = default_industries
    st.session_state.scenario = default_scenario
    st.session_state.max_adbudget = default_max_budget
    st.experimental_rerun()


# Фільтри з використанням session_state
st.session_state.year = st.sidebar.selectbox("Оберіть рік", sorted(df["Year"].unique()), index=sorted(df["Year"].unique()).index(st.session_state.year))
st.session_state.regions = st.sidebar.multiselect("Оберіть регіони", df["Region"].unique(), default=st.session_state.regions)
st.session_state.industries = st.sidebar.multiselect("Оберіть галузі", df["Industry"].unique(), default=st.session_state.industries)
st.session_state.scenario = st.sidebar.radio("Сценарій", df["Scenario"].unique(), index=list(df["Scenario"].unique()).index(st.session_state.scenario))

st.session_state.max_adbudget = st.sidebar.slider(
    "Максимальний рекламний бюджет",
    min_value=int(df["AdBudget"].min()),
    max_value=int(df["AdBudget"].max()),
    value=st.session_state.max_adbudget,
    step=1000
)
# Чекбокси для відображення
show_map = st.sidebar.checkbox("Показати карту компаній")
show_scatter = st.sidebar.checkbox("Показати графік ROI vs Investment")

# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown(" **Інструкція**: \nФільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.")
st.sidebar.markdown(" **Автор**: Lazar_Iryna")

# ---------------------------------
# Фільтрація
# ---------------------------------
df_filtered = df[
    (df["Year"] == st.session_state.year) &
    (df["Region"].isin(st.session_state.regions)) &
    (df["Industry"].isin(st.session_state.industries)) &
    (df["Scenario"] == st.session_state.scenario) &
    (df["AdBudget"] <= st.session_state.max_adbudget)
]


# ---------------------------------
# 🧾 Основна панель
# ---------------------------------

st.title("📊 Економічний дашборд компаній")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} компаній")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered_companies.csv",
    mime="text/csv"
)

# Таблиця результатів
st.dataframe(df_filtered)

# Карта компаній
if show_map:
    st.subheader("🗺 Географія компаній")
    st.map(df_filtered[['Latitude', 'Longitude']])

# Scatter-графік ROI ~ Investment
if show_scatter:
    st.subheader("📉 ROI ~ Investment (Altair)")
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x='Investment:Q',
        y='ROI:Q',
        color='Industry:N',
        tooltip=['Company', 'Investment', 'ROI']
    ).interactive().properties(
        width=700, height=400
    )
    st.altair_chart(chart, use_container_width=True)
